server:
  port: 8080
  context-path: /seckill
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: root
  http:
      encoding:
        charset: utf-8
        enabled: true
        force: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    com.wgt: debug